-- ============================================================================
-- 1. CREATE TABLES (Membuat Struktur Database)
-- ============================================================================

-- Tabel Produk (products)
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    excerpt TEXT,
    content TEXT,
    cover_image TEXT,
    link TEXT,
    price TEXT,
    is_featured BOOLEAN DEFAULT false,
    tags TEXT, -- Disimpan sebagai stringified JSON array
    published_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabel Proyek/Galeri (projects)
CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    summary TEXT,
    description TEXT,
    content TEXT,
    cover_image TEXT,
    cover_alt TEXT,
    tech TEXT,   -- Disimpan sebagai stringified JSON array
    role TEXT,
    year TEXT,
    featured BOOLEAN DEFAULT false,
    client TEXT,
    duration TEXT,
    links TEXT,  -- Disimpan sebagai stringified JSON object
    images TEXT, -- Disimpan sebagai stringified JSON array
    published_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Tabel Artikel Blog (blog_posts)
CREATE TABLE IF NOT EXISTS blog_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    excerpt TEXT,
    content TEXT,
    cover_image TEXT,
    read_time INTEGER DEFAULT 0,
    is_featured BOOLEAN DEFAULT false,
    tags TEXT, -- Disimpan sebagai stringified JSON array
    published_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================================
-- TRUNCATE & RESTART IDENTITY
-- ============================================================================
-- Opsional: Membersihkan data lama agar ID kembali dari 1 jika script dijalankan ulang.
TRUNCATE TABLE products, projects, blog_posts RESTART IDENTITY;

-- ============================================================================
-- 2. INSERT DATA (Mengisi Data Contoh ke Database minimal 3 per tabel)
-- Catatan: Menggunakan URL gambar absolut (placeholder online) agar gambar
-- langsung muncul saat CRUD (preview) tanpa perlu mengunggah secara manual dulu.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Insert Data: Produk
-- ----------------------------------------------------------------------------
INSERT INTO products (title, slug, excerpt, content, cover_image, link, price, is_featured, tags) VALUES
('Paket Seminar Basic', 'paket-seminar-basic', 'Paket hemat untuk seminar skala kecil hingga menengah.', 'Paket ini mencakup Tas Spunbond, Blocknote A5, Pulpen Standar, dan ID Card. Sangat cocok untuk acara kampus atau workshop singkat.', 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&q=80&w=800', '/contact', 'Rp 25.000 / pax', true, '["basic", "hemat", "tas spunbond", "seminar"]'),
('Paket Seminar Profesional', 'paket-seminar-profesional', 'Pilihan terpopuler dengan tas kanvas dan notes eksklusif.', 'Dilengkapi dengan Tas Kanvas tebal, Blocknote Hardcover, Pulpen Metal, Tumbler Plastik, dan Lanyard. Ideal untuk konferensi tingkat nasional.', 'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&q=80&w=800', '/contact', 'Rp 75.000 / pax', true, '["profesional", "kanvas", "tumbler", "konferensi"]'),
('Paket Seminar Premium Eksklusif', 'paket-seminar-premium', 'Paket mewah dengan ransel laptop dan merchandise premium.', 'Cocok untuk tamu VIP. Berisi Ransel Laptop, Buku Agenda Kulit Premium, Flashdisk Custom 16GB, Tumbler Suhu Stainless, dan Kaos Polo.', 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&q=80&w=800', '/contact', 'Rp 250.000 / pax', true, '["premium", "vip", "ransel", "flashdisk"]'),
('Souvenir Tumbler Custom', 'souvenir-tumbler-custom', 'Tumbler stainless steel dengan grafir logo perusahaan.', 'Tumbler tahan panas/dingin hingga 12 jam. Dapat digrafir dengan logo atau nama peserta menggunakan teknologi laser presisi.', 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&q=80&w=800', '/contact', 'Rp 45.000 / pcs', false, '["tumbler", "souvenir", "custom logo"]');

-- ----------------------------------------------------------------------------
-- Insert Data: Proyek/Galeri
-- ----------------------------------------------------------------------------
INSERT INTO projects (title, slug, summary, description, content, cover_image, cover_alt, tech, role, year, featured, client, duration, links, images) VALUES
('Seminar Nasional Pendidikan 2026', 'seminar-nasional-pendidikan-2026', 'Penyediaan 500 paket seminar kit standar untuk peserta dari seluruh Indonesia.', 'Kami bangga menjadi mitra pengadaan seminar kit untuk Seminar Nasional Pendidikan 2026 yang dihadiri oleh guru dan praktisi pendidikan dari seluruh Nusantara.', 'Acara ini membutuhkan pengiriman yang cepat dan presisi. Kami menyediakan 500 tote bag sablon, blocknote, pulpen, dan sertifikat cetak yang diselesaikan dalam waktu 1 minggu.', 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&q=80&w=800', 'Suasana Seminar Nasional', '["Tote Bag", "Blocknote", "Sertifikat"]', 'Vendor Merchandise', '2026', true, 'Universitas Indonesia', '1 Minggu', '{}', '[]'),
('Konferensi Teknologi & Inovasi (TechCon)', 'techcon-2026', 'Distribusi 1000 paket premium VIP untuk startup founder dan investor.', 'TechCon membutuhkan perlengkapan yang merepresentasikan inovasi dan kemewahan. Kami mensuplai ransel laptop dan tumbler pintar.', 'Peserta sangat menyukai tumbler pintar dengan pengukur suhu yang kami berikan. Logo TechCon digrafir elegan pada setiap tumbler.', 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&q=80&w=800', 'TechCon 2026 VIP Kit', '["Ransel Laptop", "Smart Tumbler", "Flashdisk Custom"]', 'Vendor Utama', '2026', true, 'TechCorp Indonesia', '3 Minggu', '{}', '[]'),
('Workshop Digital Marketing', 'workshop-digital-marketing', 'Pengadaan 200 paket alat tulis dan ID card eksklusif.', 'Untuk workshop intensif selama 2 hari, peserta membutuhkan alat tulis yang nyaman dan ID Card yang kokoh.', 'Kami mendesain khusus Lanyard dengan warna brand klien dan blocknote ring yang mudah digunakan selama sesi praktek digital marketing.', 'https://images.unsplash.com/photo-1531498860502-7c67cf02f657?auto=format&fit=crop&q=80&w=800', 'Alat tulis workshop', '["Lanyard Custom", "Blocknote Ring", "Pulpen Stylus"]', 'Vendor Sablon & Cetak', '2025', false, 'Marketer ID', '5 Hari', '{}', '[]');

-- ----------------------------------------------------------------------------
-- Insert Data: Artikel Blog
-- ----------------------------------------------------------------------------
INSERT INTO blog_posts (title, slug, excerpt, content, cover_image, read_time, is_featured, tags) VALUES
('Panduan Lengkap Memilih Paket SeminarKit', 'panduan-memilih-seminarkit', 'Jangan salah pilih! Ketahui cara menyesuaikan paket dengan budget.', 'Memilih perlengkapan seminar seringkali membingungkan. Pertama, pastikan siapa target audiens Anda. Jika mahasiswa, paket basic sudah cukup...', 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=800', 5, true, '["Panduan", "Tips", "Budgeting"]'),
('Mengapa Souvenir Ramah Lingkungan Diminati?', 'souvenir-ramah-lingkungan', 'Tren eco-friendly kini merambah ke dunia merchandise acara.', 'Menggunakan tote bag dari bahan daur ulang tidak hanya menyelamatkan bumi, tetapi juga meningkatkan citra positif perusahaan Anda...', 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=800', 4, true, '["Eco-Friendly", "Tren", "Green Event"]'),
('Tips Menghemat Budget Merchandise', 'tips-menghemat-budget-merchandise', 'Anda punya budget terbatas? Ini rahasia agar kit Anda tetap elegan.', 'Fokuslah pada desain, bukan sekadar harga barang. Sebuah tote bag blacu murah akan terlihat sangat premium jika desain sablonnya minimalis...', 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&q=80&w=800', 3, false, '["Budget", "Desain", "Tips"]');

